---
- include_role:
    name: logrotate

- name: Pass variables to role logrotate
  include_role:
    name: logrotate
  vars:
    logrotate_scripts:
      - name: nginx-teste
        path: /var/log/nginx/access.log
        options:
          - daily
          - weekly
          - size 1k
          - rotate 7
          - missingok
          - compress
          - delaycompress
          - copytruncate

...