---
/export/logs/pagseguro-fe/*.log.????-??-??-?? {
    su root nobody
    rotate 50
    daily
    compress
    nocreate
    nodateext
    dateext
    dateformat 
    ifempty
    missingok
    start 0
    size 0
    lastaction        
        mv /export/logs/pagseguro-fe/*.log.*.gz /export/logs_gz/pagseguro-fe/
        find /export/logs/pagseguro-fe/ -name "*.log.*.gz" -type f -mtime +50 -exec rm {} \;
    endscript
}
...
